name: Java CI with Maven

on:
#    schedule:
#      - cron:  "5 * * * *"
#    workflow_dispatch:
 push:
    branches: [ main ]
 # pull_request:
 #   branches: [ main ]

env: 
  art_pass: ${{ secrets.ARTIFACTORY_PASSWORD }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Calling password
      run: echo $art_pass
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK 11
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Test Cases
      run: mvn test --file pom.xml
